version: '3'

networks:
  zshort:

services:
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    # change outside port to not conflict with my localhost
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/log/nginx
      - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - zshort

  #MySQL Service
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
#    restart: unless-stopped
    restart: always
    tty: true
    ports:
      - "3316:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: zshort
      MYSQL_USER: zshortuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
#      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - zshort

  app:
    build:
      context: .
      dockerfile: build/php/Dockerfile
    container_name: app
    volumes:
      - ./src:/var/www/html
      #Todo: it is wrong to add all logs in same folder
      # it is for  "dev and proof of concept"
      - ./logs:/var/log
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    networks:
      - zshort

# this is much more but make life easy
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - app
    networks:
      - zshort

#  phpmyadmin:
#    depends_on:
#      - mysql
#    links:
#      - mysql
#    image: phpmyadmin/phpmyadmin
#    restart: always
#    container_name: phpmyadmin
#    ports:
#      - 8082:80
#    environment:
#      PMA_HOST: mysql
#      MYSQL_ROOT_PASSWORD: password
#    networks:
#      - zshort